spring:
    application:
        name: expgateway
server:
    port: 1000
    reactive:
        session:
            timeout: 20m

logging:
    level:
        "[org.springframework.cloud.gateway]": DEBUG
        "[org.springframework.http.server.reactive]": DEBUG
        "[org.springframework.web.reactive]": DEBUG
        "[org.springframework.boot.autoconfigure.web]": DEBUG
        "[reactor.netty]": DEBUG

        # Redis Rate Limiter (Spring Cloud Gateway)
        # org.springframework.cloud.gateway.filter.ratelimit: DEBUG
        #org.springframework.data.redis: DEBUG
        #io.lettuce.core: DEBUG
gateway:
    userservice: lb://userservice
    categoryservice: lb://categoryservice
    expenseservice: lb://expenseservice
    uiservice: lb://uiservice
    authhost: http://host.docker.internal:8080/

eureka:
    client:
        service-url:
            defaultZone: http://host.docker.internal:8761/eureka
